"""Record the fixtures `MOCK_LLM=true` replays.

CLAUDE.md rule 8: the full demo runs offline from recorded fixtures, and
that must work from day one. This is how the recordings get made.

TWO MODES, AND THE DIFFERENCE MATTERS.

    --live      calls the Claude API and records what it actually said.
                Needs ANTHROPIC_API_KEY. These are recordings.

    --offline   synthesises the responses from a deterministic stand-in
                and records those instead. These are NOT recordings, and
                every fixture written this way says so in its `note`
                field and carries `"synthetic": true`.

The offline mode exists because a repository has to be buildable and
testable without an API key, not because a stand-in is as good as the
model. Be clear-eyed about what the offline fixtures prove and what they
do not:

  they DO prove the pipeline — batching, the content-hash cache, the
  parsing, the counting, the chi-square, and the rule that no number
  reaches a case from a model response.

  they DO NOT prove the model's judgement. A fixture written offline says
  what the stand-in decided about a note, not what Haiku would decide.

The stand-in is a keyword matcher over the document text. It is
deliberately dumb, deliberately confined to this module, and deliberately
never imported by anything the engine runs — `llm/classify.py` has no idea
it exists. Re-record with `--live` before quoting a classification
accuracy figure to anybody.

Usage:

    python -m llm.record_fixtures --offline
    python -m llm.record_fixtures --live
"""

from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Sequence

from llm.classify import Document, build_request
from llm.hypothesise import build_request as build_hypothesis_request
from llm.provider import (
    FIXTURE_DIR,
    LLMRequest,
    LLMResponse,
    get_provider,
    record_fixture,
)

#: What an offline fixture is labelled with, so nobody mistakes one for a
#: recording. Grep for it before publishing a number about the classifier.
SYNTHETIC_NOTE = (
    "SYNTHETIC — generated by llm/record_fixtures.py --offline from a keyword "
    "stand-in, NOT a recording of a live model. Re-record with --live before "
    "quoting any classification accuracy."
)


# ===========================================================================
# The stand-in
# ===========================================================================
#
# Keyword rules over the document text, one per hypothesis tag. They exist
# only so the offline demo has something to replay. Nothing in engine/ or
# in llm/classify.py can reach them.

_RULES: dict[str, tuple[re.Pattern[str], ...]] = {
    "stock_out": tuple(
        re.compile(pattern, re.IGNORECASE)
        for pattern in (
            r"not available",
            r"nahi hai",
            r"khatam",
            r"no stock",
            r"stock out",
            r"stock nil",
            r"shelf .*empty",
            r"replenishment truck did not",
            r"size .*(gone|not there)",
            r"sizes .*(gone|out)",
        )
    ),
    "staffing_shortfall": tuple(
        re.compile(pattern, re.IGNORECASE)
        for pattern in (r"staff on leave", r"waited a long time", r"counter queue")
    ),
    "competitor_action": tuple(
        re.compile(pattern, re.IGNORECASE)
        for pattern in (r"discount this week", r"offer nearby", r"went there instead")
    ),
    "price_increase": tuple(
        re.compile(pattern, re.IGNORECASE)
        for pattern in (r"prices seem higher", r"full price")
    ),
    "footfall_decline": tuple(
        re.compile(pattern, re.IGNORECASE)
        for pattern in (r"road work", r"road closure", r"drop in walk-ins")
    ),
}

_DATE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")

#: Confidence the stand-in reports. High for a keyword hit because the
#: keywords are unambiguous; the `none` case is confident too, and both
#: are the stand-in's own numbers, not a model's.
_HIT_CONFIDENCE = 0.92
_MISS_CONFIDENCE = 0.88


def _stand_in_tag(text: str, tags: Sequence[str], null_tag: str) -> dict[str, object]:
    for tag in tags:
        for pattern in _RULES.get(tag, ()):
            if pattern.search(text):
                found = _DATE.search(text)
                return {
                    "hypothesis_tag": tag,
                    "event_date": found.group(1) if found else None,
                    "confidence": _HIT_CONFIDENCE,
                }
    return {
        "hypothesis_tag": null_tag,
        "event_date": None,
        "confidence": _MISS_CONFIDENCE,
    }


def synthesise_classification(
    documents: Sequence[Document], tags: Sequence[str], null_tag: str
) -> str:
    """The reply the stand-in would have given for one batch."""
    payload = [
        {"id": document.document_id, **_stand_in_tag(document.text, tags, null_tag)}
        for document in documents
    ]
    return json.dumps(payload, ensure_ascii=False)


#: The long-tail candidates the stand-in proposes. Written out rather than
#: generated: a keyword matcher cannot invent a hypothesis, and pretending
#: otherwise would be worse than saying so.
_LONG_TAIL = [
    {
        "label": "Dispatch backlog at the distribution centre",
        "description": "Stock left the DC late enough that stores traded thin for days.",
        "testable_by": "dispatch and delivery timestamps in the TMS",
    },
    {
        "label": "Assortment reset mid-period",
        "description": "A planogram change removed lines that were still selling.",
        "testable_by": "the ranged-assortment master by store and week",
    },
    {
        "label": "Payment terminal downtime",
        "description": "Card terminals were down long enough to lose completed baskets.",
        "testable_by": "till uptime logs against transaction gaps",
    },
]


def synthesise_hypotheses() -> str:
    return json.dumps(_LONG_TAIL, ensure_ascii=False)


# ===========================================================================
# Recording
# ===========================================================================


@dataclass(frozen=True)
class Recording:
    request: LLMRequest
    text: str
    note: str
    synthetic: bool


def _write(recording: Recording, fixtures_dir: Path) -> Path:
    response = LLMResponse(
        text=recording.text,
        model=recording.request.model,
        stop_reason="end_turn",
        request_fingerprint=recording.request.fingerprint(),
    )
    path = record_fixture(
        recording.request, response, fixtures_dir=fixtures_dir, note=recording.note
    )
    if recording.synthetic:
        payload = json.loads(path.read_text(encoding="utf-8"))
        payload["synthetic"] = True
        path.write_text(
            json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    return path


def record_for_case(
    *,
    live: bool,
    fixtures_dir: Path | None = None,
    database: str | Path | None = None,
) -> list[Path]:
    """Record every fixture the demo case needs.

    Walks the same code path the engine walks — the same request builder,
    the same batching, the same content hashes — so a fixture recorded here
    is a fixture the engine will find.
    """
    from engine.db import DEFAULT_DB_PATH, connect
    from engine.gather.gate import GatherRequest
    from engine.gather.hypotheses import screen
    from engine.gather.unstructured import load_documents
    from engine.db import warehouse_clock
    from security.policy import User
    from semantic_layer.schema import load_semantic_layer

    fixtures_dir = Path(fixtures_dir) if fixtures_dir else FIXTURE_DIR
    layer = load_semantic_layer()
    spec = layer.gather
    user = User(user_id="U008", persona="analyst")
    connection = connect(database or DEFAULT_DB_PATH, read_only=not live)
    provider = get_provider() if live else None

    written: list[Path] = []
    #: Screening contexts the demo and the suite both exercise. Each needs
    #: its own long-tail fixture, because the request names the KPI and the
    #: candidates already under consideration.
    contexts = (
        ("net_revenue", "West", "2025-11", "down"),
        ("qcomm_fulfilment_rate", "All-India", "2025-11", "down"),
        ("conversion_rate", "East", "2025-10", "down"),
        ("net_revenue", "South", "2025-09", "down"),
    )
    request = GatherRequest(
        kpi="net_revenue",
        scope="West",
        grain="monthly",
        period="2025-11",
        period_start=date(2025, 11, 1),
        period_end=date(2025, 11, 30),
        comparison_start=date(2025, 10, 1),
        comparison_end=date(2025, 10, 31),
    )

    # --- the long-tail calls -----------------------------------------------
    for kpi, scope, period, direction in contexts:
        graph_tags = sorted(
            name
            for name, template in layer.causal_graph.hypotheses.items()
            if kpi in template.affects
            and name not in spec.hypotheses.already_removed
        )
        hypothesis_request = build_hypothesis_request(
            kpi, scope, period, direction,
            graph_tags, spec.hypotheses.sources.long_tail,
        )
        written.append(
            _write(
                Recording(
                    request=hypothesis_request,
                    text=(
                        provider.complete(hypothesis_request).text
                        if live
                        else synthesise_hypotheses()
                    ),
                    note=f"long-tail hypothesis generation, {kpi}/{scope}/{period}"
                    if live
                    else SYNTHETIC_NOTE,
                    synthetic=not live,
                ),
                fixtures_dir,
            )
        )

    # --- the classification batches ---------------------------------------
    clock = warehouse_clock(connection, layer)
    screening = screen(
        connection, user, layer,
        kpi=request.kpi, scope=request.scope, grain=request.grain,
        period=request.period, direction="down", now=clock,
        provider=_ReplayOnly(fixtures_dir),
    )
    tags = screening.tags
    classification = spec.unstructured.classification

    for _name, corpus in sorted(spec.unstructured.corpora.items()):
        documents = load_documents(
            connection, user, layer, corpus,
            kpi=request.kpi, scope=request.scope,
            period_start=request.period_start, period_end=request.period_end,
        )
        model = LLMRequest.for_task(classification.task, system="", messages=()).model
        seen: dict[str, Document] = {}
        for document in documents:
            seen.setdefault(document.content_hash(tags, classification, model), document)

        distinct = list(seen.values())
        for start in range(0, len(distinct), classification.batch_size):
            batch = distinct[start : start + classification.batch_size]
            call = build_request(batch, tags, classification)
            written.append(
                _write(
                    Recording(
                        request=call,
                        text=(
                            provider.complete(call).text
                            if live
                            else synthesise_classification(
                                batch, tags, classification.null_tag
                            )
                        ),
                        note=f"classification batch, {corpus.table}, case #2451"
                        if live
                        else SYNTHETIC_NOTE,
                        synthetic=not live,
                    ),
                    fixtures_dir,
                )
            )

    written.extend(record_narratives(live=live, fixtures_dir=fixtures_dir, layer=layer))

    connection.close()
    return written


def record_narratives(
    *,
    live: bool,
    fixtures_dir: Path | None = None,
    layer=None,
) -> list[Path]:
    """One fixture per scenario per persona. Five by three, fifteen calls.

    Walks the same request builder `llm/narrate.py` walks, so a fixture
    recorded here is a fixture the narrator will find. The offline text
    comes from the template walker in `llm/stand_in.py` and is labelled
    SYNTHETIC; the live text comes from Sonnet and is not.

    NO REGENERATION FIXTURE IS RECORDED, and that is a statement about the
    recording rather than about the loop. The regeneration request is
    built from the FEEDBACK on a failed first pass, so it only exists when
    a first pass fails. All fifteen of these ground first time, so the
    second call is never made and a fixture for it would be a recording of
    something that never happens. The loop itself is exercised against
    injected failures in tests/test_grounding.py, where the failure is the
    point.
    """
    from engine.verdict.canonical import build as build_canonical
    from engine.verdict.casefile import narrative_document
    from llm.casefiles import CASE_IDS
    from llm.narrate import build_request as build_narrative_request
    from llm.stand_in import synthesise_narrative

    if layer is None:
        from semantic_layer.schema import load_semantic_layer

        layer = load_semantic_layer()
    fixtures_dir = Path(fixtures_dir) if fixtures_dir else FIXTURE_DIR
    provider = get_provider() if live else None

    # THE DOCUMENT MUST BE THE ONE THE API SENDS. A fixture is keyed by a
    # content hash of the request, so recording against a case file
    # assembled differently from the one served produces fifteen fixtures
    # that never match. The canonical builder is what the API seeds its
    # store from, and `narrative_document` is what both hand the narrator.
    connection, user = _warehouse()

    written: list[Path] = []
    for case_id in CASE_IDS:
        adjudication = narrative_document(
            build_canonical(
                case_id, connection=connection, user=user, layer=layer
            ).case_file
        )
        for persona in sorted(layer.narrate.personas):
            call = build_narrative_request(adjudication, persona, layer)
            written.append(
                _write(
                    Recording(
                        request=call,
                        text=(
                            provider.complete(call).text
                            if live
                            else synthesise_narrative(adjudication, persona, layer)
                        ),
                        note=f"narrative, case #{case_id}, persona {persona}"
                        if live
                        else SYNTHETIC_NOTE,
                        synthetic=not live,
                    ),
                    fixtures_dir,
                )
            )
    return written


def _warehouse():
    """A connection and a reader for the canonical build.

    The recommendation half of a case file is priced against the
    warehouse. Without one the case files come back without it, the
    document differs from the one the API sends, and the fixtures miss —
    so the recorder opens the warehouse rather than skipping it.
    """
    from engine.db import DEFAULT_DB_PATH, connect
    from security.policy import User

    if not DEFAULT_DB_PATH.exists():
        raise SystemExit(
            f"no warehouse at {DEFAULT_DB_PATH}. Run `make seed` first: the "
            "narrative fixtures are keyed by a document that includes the "
            "priced recommendation."
        )
    # Read-only, to match the connection  opened in the
    # same process: DuckDB refuses a second handle to one file under a
    # different configuration. Nothing here writes.
    return (
        connect(DEFAULT_DB_PATH, read_only=True),
        User(user_id="system", persona="analyst"),
    )


class _ReplayOnly:
    """Provider used while recording: replays the long-tail fixture just written."""

    name = "replay-only"

    def __init__(self, fixtures_dir: Path) -> None:
        from llm.provider import MockProvider

        self._mock = MockProvider(fixtures_dir)

    def complete(self, request: LLMRequest):
        return self._mock.complete(request)


def main() -> None:  # pragma: no cover - entry point
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--live", action="store_true", help="call the API and record it")
    mode.add_argument(
        "--offline",
        action="store_true",
        help="synthesise from the keyword stand-in and label the fixtures SYNTHETIC",
    )
    parser.add_argument("--fixtures-dir", default=None)
    args = parser.parse_args()

    if args.live and not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("--live needs ANTHROPIC_API_KEY")

    written = record_for_case(live=args.live, fixtures_dir=args.fixtures_dir)
    label = "recorded" if args.live else "SYNTHESISED (not recordings)"
    print(f"{len(written)} fixtures {label}:")
    for path in written:
        print(f"  {path.name}")


if __name__ == "__main__":  # pragma: no cover
    main()


__all__ = [
    "SYNTHETIC_NOTE",
    "Recording",
    "record_for_case",
    "record_narratives",
    "synthesise_classification",
    "synthesise_hypotheses",
]
